import type { AzureMetricSummary, AzureReportDimension } from "./report-metrics.mjs";

export type PatternType = "GRAMMAR" | "WORD_CHOICE" | "FALSE_COGNATE" | "STRUCTURE";
export type ProgressRecord = {
  id: string;
  status: string;
  targetRole: string;
  seniority: string | null;
  startedAt: string | null;
  completedAt: string | null;
  createdAt: string;
  answerCount: number;
  feedback: { status: "pending" | "ready" | "unavailable"; azureSummary: AzureMetricSummary | null; analysis: unknown } | null;
};
export type ProgressDimension = { key: string; kind: "pattern" | "voice"; label: string; fullLabel: string; value: number; detail: string };
export type ProgressExample = { evidence: string; suggestion: string; rephrasedExample: string; date: string | null; role: string };
export type ProgressCommonError = { type: PatternType; label: string; count: number; sessionCount: number; rate: number | null; trend: "up" | "down" | "steady" | "unknown"; share: number; examples: ProgressExample[] };
export type ProgressStudyTopic = { id: string; kind: "english" | "technical"; patternType?: PatternType; title: string; count: number; sessionCount: number; exercise: string; exerciseSource: "report" | "default"; focuses: string[]; rank: number };
export type ProgressPoint = { id: string; date: string | null; label: string; value: number };
export type ProgressSeriesKey = "patterns" | "gaps" | AzureReportDimension;
export type ProgressSessionRow = { id: string; date: string | null; role: string; seniority: string | null; durationMs: number | null; answerCount: number; reportStatus: "ready" | "pending" | "unavailable" | "none"; patternCount: number | null };
export type ProgressInsights = {
  sessionCount: number;
  practiceMs: number | null;
  answerCount: number;
  latestRole: string | null;
  latestSeniority: string | null;
  lastPracticeAt: string | null;
  reportReadyCount: number;
  analyzedSessions: number;
  analyzedAnswers: number;
  dimensions: ProgressDimension[];
  attentionDimension: ProgressDimension | null;
  commonErrors: ProgressCommonError[];
  studyTopics: ProgressStudyTopic[];
  series: Record<ProgressSeriesKey, ProgressPoint[]>;
  weekly: Array<{ start: string; label: string; count: number }>;
  sessionsUntilTrends: number;
  sessions: ProgressSessionRow[];
};
export const patternTypes: PatternType[];
export const patternTypeCopy: Record<PatternType, { label: string; short: string }>;
export const voiceDimensionCopy: Record<AzureReportDimension, { label: string; short: string }>;
export const defaultExercises: Record<PatternType, string>;
export const minAnswersForProfile: number;
export const minSessionsForTrends: number;
export function sessionDurationMs(record: { startedAt: string | null; completedAt: string | null }): number | null;
export function weeklySessions(sessions: Array<{ time: number | null }>, now?: number): ProgressInsights["weekly"];
export function buildProgressInsights(records: ProgressRecord[], options?: { now?: number }): ProgressInsights;
